In [1]:
import numpy as np

In [4]:
print(np.version)
print(np.show_config())

<module 'numpy.version' from 'D:\\anaconda\\lib\\site-packages\\numpy\\version.py'>
mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'D:/anaconda\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/anaconda\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_li

In [11]:
a = np.zeros(10)
b = np.empty(10)
print(a)
print(b)
b  #输出的b和print（b）为什么不一致，待查

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
import sys 
s = np.ones((3,2)) #非单列的需加括号
print('%d bytes' %(sys.getsizeof(s))) #为什么两种不一致
print("%d bytes" % (s.size * s.itemsize)) #size以什么为基础衡量

104 bytes
48 bytes


In [21]:
%run `python -c "import numpy; numpy.info(numpy.add)"`#没看懂

ERROR:root:File `'`python.py'` not found.


In [28]:
a = np.zeros(10)
a[4]=1  #这是操作，不能直接print
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [30]:
#7
#a = np.random.randint(10,49)
#print(a)  产生10-49的随机数
Z = np.arange(10,50)
print(Z)   #输出从10开始的50个数

48


In [43]:
#8
a = np.array([1,3,5,7])
a = a[::-1]
print(a) 

[7 5 3 1]


In [46]:
#9
#用reshape方法
#arr = np.arange(9)
#arr.shape=(3,3)
#print(arr)

Z = np.arange(9).reshape(3,3)  #arange需要带入大小，且和reshape中的大小需匹配，9=3*3
print(Z)  #reshape

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [49]:
#10
# list1 = [1,2,0,0,4,0]
# for i in list1:
#    if i > 0:
#       print(list1.index(i))
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

0
1
4


In [57]:
#11
arr = np.ones((3,3))
print(arr) #全是1元素的矩阵
arr2 = np.eye(3)
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [62]:
#12 
arr = np.random.random((3,3,3)) #1、随机数有random方法；2、为什么老是需要两个括号？？？
print(arr)

[[[0.32193361 0.15282628 0.38533506]
  [0.82939301 0.23170451 0.13095014]
  [0.32604185 0.60358958 0.44579805]]

 [[0.70174891 0.66411244 0.46363668]
  [0.7660596  0.3710749  0.61331447]
  [0.9409406  0.435368   0.48940658]]

 [[0.18912761 0.17543709 0.71967554]
  [0.82649116 0.79891723 0.19457321]
  [0.57881171 0.16477854 0.92783983]]]


In [65]:
#13
arr = np.random.random((3,3))
print(arr)
Amin,Amax = arr.min(),arr.max() #两个赋值可以分别写
print(Amin,Amax)

[[0.98389894 0.13828508 0.47104925]
 [0.33176901 0.05343673 0.34620662]
 [0.01181063 0.38873146 0.78911875]]
0.011810627570051024 0.9838989418184831


In [67]:
#14
#均值方法mean()
A = np.random.random(30)
#print(A.sum()/len(A))
print(A.mean())

0.5106541816619129


In [69]:
#15
#先生成、改元素；索引1和-1的使用
A = np.ones((6,6))
A[1:-1,1:-1] = 0
print(A)

[[1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [78]:
#16
#pad方法！！！
A = np.arange(9).reshape(3,3)
A = np.pad(A,pad_width=1,mode='constant',constant_values='0')
print(A)

[[0 0 0 0 0]
 [0 0 1 2 0]
 [0 3 4 5 0]
 [0 6 7 8 0]
 [0 0 0 0 0]]


In [85]:
#17
#A = np.nan ->nan  ???
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf>np.nan)
print(3 == 3*0.1)
print(np.nan in set([np.nan]))
print(np.nan-np.nan)

nan
False
False
False
True
nan


In [88]:
#18
#diag方法了解！！！
A = np.diag(1+np.arange(4),k=-1)
print(A)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [92]:
#19
#???
A = np.zeros((8,8),dtype=int)
print(A)
A[1::2,::2]=1
print(A)
A[::2,1::2]=1
print(A)

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]
 [0 0 0 0 0 0 0 0]
 [1 0 1 0 1 0 1 0]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [93]:
#20
#unravel_index
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


In [96]:
#21
#tile:第一个参数是数组，第二个参数是大小
A = np.tile(([[0,1],[1,0]]),(4,4))
print(A)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [97]:
#22
#归一化处理
A = np.random.random((5,5))
Amax,Amin = A.max(),A.min()
A = (A-Amin)/(Amax-Amin)
print(A)

[[0.53709816 0.27618843 0.34914112 0.44988581 0.        ]
 [0.55752328 0.09778054 0.60088644 0.53145301 0.23426051]
 [0.8699644  0.51252437 0.7940935  0.70907315 0.26232172]
 [0.41448779 0.2373062  0.09390149 0.10133515 1.        ]
 [0.74603947 0.69197015 0.64714173 0.17145296 0.71054333]]


In [98]:
#23
#dtype?ubyte?
color = np.dtype([('r',np.ubyte,1),
                 ('g',np.ubyte,1),
                 ('b',np.ubyte,1),
                 ('a',np.ubyte,1)])

In [100]:
#24:
#*为对应元素相乘
A = np.random.random((5,3))
B = np.random.random((3,2))
C = A @ B
print(C)

[[0.99161055 0.22240077]
 [1.64701641 0.29882027]
 [0.84811231 0.15384347]
 [0.95158041 0.2000867 ]
 [1.51197995 0.31766527]]


In [101]:
#25
A = np.arange(1,10)
A[(A>=3)&(A<=8)]*=-1  #A数组直接和3比较？？？
print(A)

[ 1  2 -3 -4 -5 -6 -7 -8  9]


In [102]:
#26
#sum传入两个参数的意思？？？
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [107]:
#27
#还没查
Z=([1,2,3,4,5])
Z**Z
2 << Z >> 2
Z <- Z
1j*Z 
Z/1/1
Z<Z>Z

TypeError: can't multiply sequence by non-int of type 'list'

In [108]:
#28
#??
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-2.14748365e+09]


D:\anaconda\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
D:\anaconda\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


In [111]:
#29
#uniform、copysign、ceil
A = np.random.uniform(-10,10,10)
print(A)
print(np.copysign(np.ceil(np.abs(A)),A))

[-1.02124721  4.68711517  5.02418517 -4.20453209  0.52287755  8.59739402
 -9.53646207  1.05874975 -5.39518339  7.87866795]
[ -2.   5.   6.  -5.   1.   9. -10.   2.  -6.   8.]


In [117]:
#30
#intersect1d比较大小
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(Z1)
print(Z2)
print(np.intersect1d(Z1,Z2))

[4 4 2 1 4 1 7 1 9 0]
[3 1 1 4 0 6 1 1 2 8]
[0 1 2 4]


In [118]:
#31
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-118-4ac962bdd449>, line 9)

In [119]:
#np.sqrt(-1) == np.emath.sqrt(-1)

False

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')