In [5]:
import pandas as pd

In [6]:
obj = pd.Series([4,7,-5,3])

In [7]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [8]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2 = pd.Series([5,8,9,5],index = ['b','s','a','i'])

In [11]:
obj2

b    5
s    8
a    9
i    5
dtype: int64

In [12]:
obj2.index

Index(['b', 's', 'a', 'i'], dtype='object')

In [13]:
obj2['b']

5

In [14]:
obj2[obj2>7]

s    8
a    9
dtype: int64

In [15]:
obj2 * 2

b    10
s    16
a    18
i    10
dtype: int64

In [16]:
import numpy as np
np.exp(obj2)

b     148.413159
s    2980.957987
a    8103.083928
i     148.413159
dtype: float64

In [17]:
's' in obj2

True

In [18]:
'p' in obj2

False

In [19]:
sdata = {'a':1,'b':2,'c':3}

In [20]:
obj3 = pd.Series(sdata)

In [21]:
obj3

a    1
b    2
c    3
dtype: int64

In [22]:
zim = ['b','c','e','t']

In [23]:
obj4 = pd.Series(sdata,index=zim)

In [24]:
obj4

b    2.0
c    3.0
e    NaN
t    NaN
dtype: float64

In [25]:
pd.isnull(obj4)

b    False
c    False
e     True
t     True
dtype: bool

In [26]:
pd.notnull(obj4)

b     True
c     True
e    False
t    False
dtype: bool

In [27]:
obj4.isnull()

b    False
c    False
e     True
t     True
dtype: bool

In [28]:
obj3 + obj4

a    NaN
b    4.0
c    6.0
e    NaN
t    NaN
dtype: float64

In [29]:
obj4.name = 'population'

In [30]:
obj4.index.name = 'state'

In [31]:
obj4

state
b    2.0
c    3.0
e    NaN
t    NaN
Name: population, dtype: float64

In [32]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [33]:
obj.index = ['Bob','Lucy','Jeff','Rayn']

In [34]:
obj

Bob     4
Lucy    7
Jeff   -5
Rayn    3
dtype: int64

In [35]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada','Nevada'],'year':[2001,2002,2003,2002,2001,2006],'pop':[1.1,2.3,2.6,3.3,2.2,1.2]}

In [36]:
data

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
 'year': [2001, 2002, 2003, 2002, 2001, 2006],
 'pop': [1.1, 2.3, 2.6, 3.3, 2.2, 1.2]}

In [37]:
frame = pd.DataFrame(data)

In [38]:
frame

state  year  pop
0    Ohio  2001  1.1
1    Ohio  2002  2.3
2    Ohio  2003  2.6
3  Nevada  2002  3.3
4  Nevada  2001  2.2
5  Nevada  2006  1.2

In [39]:
frame.head()

state  year  pop
0    Ohio  2001  1.1
1    Ohio  2002  2.3
2    Ohio  2003  2.6
3  Nevada  2002  3.3
4  Nevada  2001  2.2

In [40]:
pd.DataFrame(data,columns=['year','pop','state'])

year  pop   state
0  2001  1.1    Ohio
1  2002  2.3    Ohio
2  2003  2.6    Ohio
3  2002  3.3  Nevada
4  2001  2.2  Nevada
5  2006  1.2  Nevada

In [41]:
frame2 = pd.DataFrame(data,columns=['year','pop','date','state'])

In [42]:
frame2

year  pop date   state
0  2001  1.1  NaN    Ohio
1  2002  2.3  NaN    Ohio
2  2003  2.6  NaN    Ohio
3  2002  3.3  NaN  Nevada
4  2001  2.2  NaN  Nevada
5  2006  1.2  NaN  Nevada

In [43]:
frame2.columns

Index(['year', 'pop', 'date', 'state'], dtype='object')

In [44]:
frame2.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: object

In [45]:
frame2['year']

0    2001
1    2002
2    2003
3    2002
4    2001
5    2006
Name: year, dtype: int64

In [46]:
frame2.loc[2]

year     2003
pop       2.6
date      NaN
state    Ohio
Name: 2, dtype: object

In [47]:
frame2.year=2006

In [48]:
frame2

year  pop date   state
0  2006  1.1  NaN    Ohio
1  2006  2.3  NaN    Ohio
2  2006  2.6  NaN    Ohio
3  2006  3.3  NaN  Nevada
4  2006  2.2  NaN  Nevada
5  2006  1.2  NaN  Nevada

In [49]:
frame2['pop']=np.arange(6.)

In [50]:
frame2

year  pop date   state
0  2006  0.0  NaN    Ohio
1  2006  1.0  NaN    Ohio
2  2006  2.0  NaN    Ohio
3  2006  3.0  NaN  Nevada
4  2006  4.0  NaN  Nevada
5  2006  5.0  NaN  Nevada

In [51]:
val = pd.Series([-1.2,-1.5,-1.7],index = [2,4,5])

In [52]:
frame2['pop']=val

In [53]:
frame2

year  pop date   state
0  2006  NaN  NaN    Ohio
1  2006  NaN  NaN    Ohio
2  2006 -1.2  NaN    Ohio
3  2006  NaN  NaN  Nevada
4  2006 -1.5  NaN  Nevada
5  2006 -1.7  NaN  Nevada

In [54]:
frame2['eastern']=frame2.state=='Ohio'

In [55]:
frame2

year  pop date   state  eastern
0  2006  NaN  NaN    Ohio     True
1  2006  NaN  NaN    Ohio     True
2  2006 -1.2  NaN    Ohio     True
3  2006  NaN  NaN  Nevada    False
4  2006 -1.5  NaN  Nevada    False
5  2006 -1.7  NaN  Nevada    False

In [56]:
del frame2['eastern']

In [57]:
frame2

year  pop date   state
0  2006  NaN  NaN    Ohio
1  2006  NaN  NaN    Ohio
2  2006 -1.2  NaN    Ohio
3  2006  NaN  NaN  Nevada
4  2006 -1.5  NaN  Nevada
5  2006 -1.7  NaN  Nevada

In [58]:
frame2.columns

Index(['year', 'pop', 'date', 'state'], dtype='object')

In [59]:
pop =  {'Nevada':{2001:2.4,2003:3.2},'Ohio':{2001:1.3,2002:3.3,2003:3.5}}

In [60]:
frame3 = pd.DataFrame(pop)

In [61]:
frame3

Nevada  Ohio
2001     2.4   1.3
2002     NaN   3.3
2003     3.2   3.5

In [62]:
frame3.T

2001  2002  2003
Nevada   2.4   NaN   3.2
Ohio     1.3   3.3   3.5

In [63]:
pd.DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.3
2002     NaN   3.3
2003     3.2   3.5

In [65]:
pdata = {'Ohio':frame3['Ohio'][:1],
        'Nevada':frame3['Nevada'][:2]}

In [66]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.3     2.4
2002   NaN     NaN

In [67]:
frame3.index.name = 'year'
frame3.columns.name='state'

In [68]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.3
2002      NaN   3.3
2003      3.2   3.5

In [69]:
frame3.values

array([[2.4, 1.3],
       [nan, 3.3],
       [3.2, 3.5]])

In [70]:
frame2.values

array([[2006, nan, nan, 'Ohio'],
       [2006, nan, nan, 'Ohio'],
       [2006, -1.2, nan, 'Ohio'],
       [2006, nan, nan, 'Nevada'],
       [2006, -1.5, nan, 'Nevada'],
       [2006, -1.7, nan, 'Nevada']], dtype=object)

In [76]:
obj = pd.Series(range(3),index = ['a','b','c'])

In [77]:
index = obj.index

In [78]:
index

Index(['a', 'b', 'c'], dtype='object')

In [79]:
index[1:]

Index(['b', 'c'], dtype='object')

In [80]:
index[:1]

Index(['a'], dtype='object')

In [85]:
labels = pd.Index(np.arange(3)) #pd有Index方法，第一个字母大写

In [86]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [87]:
obj2 = pd.DataFrame([1.5,2.4,3.4],labels)

In [88]:
obj2

0
0  1.5
1  2.4
2  3.4

In [89]:
obj2.index is labels

True

In [90]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.3
2002      NaN   3.3
2003      3.2   3.5

In [91]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [92]:
'Ohio' in frame3.columns

True

In [94]:
2003 in frame3.index

True

In [96]:
dup_labels = pd.Index(['foo','foo','bar','bar'])

In [97]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

In [100]:
obj = pd.Series(['4.5','7.2','-5.3','3.6'],index=['b','d','a','c'])

In [101]:
obj

b     4.5
d     7.2
a    -5.3
c     3.6
dtype: object

In [105]:
obj2 = obj.reindex(['a','b','c','d','e']) #左边仍是变量，右边代表仅对索引操作

In [106]:
obj2

a    -5.3
b     4.5
c     3.6
d     7.2
e     NaN
dtype: object

In [107]:
obj3 = pd.Series(['blue','yellow','purple'],index = [0,2,4])

In [108]:
obj3

0      blue
2    yellow
4    purple
dtype: object

In [110]:
obj3.reindex(range(6),method='ffill')#前向填充的？

0      blue
1      blue
2    yellow
3    yellow
4    purple
5    purple
dtype: object

In [111]:
frame = pd.DataFrame(np.arange(9).reshape(3,3),index = ['a','c','d'],columns = ['Ohio','Texas','California'])

In [112]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [113]:
frame2 = frame.reindex(['a','b','c','d'])

In [114]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [115]:
state = ['Texas','Utah','California']

In [116]:
frame2.reindex(columns=state)  #1、直接修改，不用赋值；2、对列索引的话加关键字

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [117]:
obj = pd.Series(np.arange(5.),index = ['a','b','c','d','e'])

In [118]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [121]:
new_obj = obj.drop('c')

In [123]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [124]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [125]:
data = pd.DataFrame(np.arange(16).reshape(4,4),index = ['Ohio','colorado','Utah','New York'],columns = ['one','two','three','four'])

In [126]:
data

one  two  three  four
Ohio        0    1      2     3
colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [127]:
data.drop(['colorado','Utah'])

one  two  three  four
Ohio        0    1      2     3
New York   12   13     14    15

In [129]:
data.drop('two',axis=1)  #drop的第一个参数为值；axis为1或column是同样的效果

one  three  four
Ohio        0      2     3
colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [131]:
data.drop('one',axis='columns') #等于列的时候双引号

two  three  four
Ohio        1      2     3
colorado    5      6     7
Utah        9     10    11
New York   13     14    15

In [132]:
data.drop(['two','four'],axis=1) #删除不是在源数据删除？？？

one  three
Ohio        0      2
colorado    4      6
Utah        8     10
New York   12     14

In [134]:
obj.drop('c',inplace=True) #inplace删除源数据

In [135]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [136]:
obj = pd.Series(np.arange(4.),index = ['a','b','c','d'])

In [137]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [138]:
obj['b']

1.0

In [139]:
obj[1]

1.0

In [140]:
obj[1:3]

b    1.0
c    2.0
dtype: float64

In [141]:
obj[['b','a','c']]

b    1.0
a    0.0
c    2.0
dtype: float64

In [142]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [144]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [146]:
obj['c':'b']

Series([], dtype: float64)

In [147]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [148]:
obj['b':'c']=5

In [149]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [150]:
data = pd.DataFrame(np.arange(16).reshape(4,4),index = ['Ohio','colorado','Utah','New York'],columns = ['one','two','three','four'])

In [151]:
data['two']

Ohio         1
colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [156]:
data[['three','one']] #如果是两列的话用列表传入！！

three  one
Ohio          2    0
colorado      6    4
Utah         10    8
New York     14   12

In [157]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
colorado    4    5      6     7

In [159]:
data[data['three']>5] #[]传入单一元素或者列表，即可输出列

one  two  three  four
colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [160]:
data<5

one    two  three   four
Ohio       True   True   True   True
colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [161]:
data[data<5]=0 #赋值改变data值

In [162]:
data

one  two  three  four
Ohio        0    0      0     0
colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [163]:
data.loc['colorado',['two','four']] #行名字表示行

two     5
four    7
Name: colorado, dtype: int32

In [165]:
data.iloc[2,[3,0,1]] #和原来行列发生变化，以行为名字，原来的列变为行

four    11
one      8
two      9
Name: Utah, dtype: int32

In [166]:
data.iloc[2] #数字表示行

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [167]:
data.iloc[[1,2],[3,0,1]] #多行和原来显示结构一样

four  one  two
colorado     7    0    5
Utah        11    8    9

In [168]:
data.loc[:'Utah','two']

Ohio        0
colorado    5
Utah        9
Name: two, dtype: int32

In [169]:
data.iloc[:,:3][data.three>5] #判断值的用【】

one  two  three
colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [170]:
ser = pd.Series(np.arange(3.))

In [172]:
ser  #索引？？

0    0.0
1    1.0
2    2.0
dtype: float64

In [173]:
ser2 = pd.Series(np.arange(3.),index = ['a','b','c'])

In [174]:
ser2[-1]

2.0

In [177]:
ser[:1]

0    0.0
dtype: float64

In [178]:
ser.loc[:1] #标签是右闭？

0    0.0
1    1.0
dtype: float64

In [179]:
ser.iloc[:1]

0    0.0
dtype: float64

In [180]:
s1 = pd.DataFrame([7.3,-2.5,3.4,1.5],index = ['a','c','d','e'])

In [181]:
s1

0
a  7.3
c -2.5
d  3.4
e  1.5

In [182]:
s2 = pd.DataFrame([-2.1,3.6,-1.5,4,3.1],index = ['a','c','e','f','g'])

In [183]:
s2

0
a -2.1
c  3.6
e -1.5
f  4.0
g  3.1

In [184]:
s1 + s2

0
a  5.2
c  1.1
d  NaN
e  0.0
f  NaN
g  NaN

In [189]:
df1 = pd.DataFrame(np.arange(9.).reshape(3,3),columns=list('bcd'),index = ['Ohio','Texas','Colorada'])

In [190]:
df2 = pd.DataFrame(np.arange(12.).reshape(4,3),columns=list('edc'),index = ['Utah','Ohio','Texas','Oregn'])

In [191]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorada  6.0  7.0  8.0

In [192]:
df2

e     d     c
Utah   0.0   1.0   2.0
Ohio   3.0   4.0   5.0
Texas  6.0   7.0   8.0
Oregn  9.0  10.0  11.0

In [193]:
df1+df2

b     c     d   e
Colorada NaN   NaN   NaN NaN
Ohio     NaN   6.0   6.0 NaN
Oregn    NaN   NaN   NaN NaN
Texas    NaN  12.0  12.0 NaN
Utah     NaN   NaN   NaN NaN

In [198]:
df1 = pd.DataFrame({'A':[1,2]})

In [199]:
df2 = pd.DataFrame({'B':[3,4]})

In [200]:
df1  #形式？？？

A
0  1
1  2

In [201]:
df2

B
0  3
1  4

In [202]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [203]:
df1 = pd.DataFrame(np.arange(12.).reshape(3,4),columns = list('abdc')) #list后面不是中括号？df

In [204]:
df2 = pd.DataFrame(np.arange(20.).reshape(4,5),columns = list('abcde'))

In [205]:
df2.loc[1,'p'] = np.nan  #含义？

In [206]:
df2

a     b     c     d     e   p
0   0.0   1.0   2.0   3.0   4.0 NaN
1   5.0   6.0   7.0   8.0   9.0 NaN
2  10.0  11.0  12.0  13.0  14.0 NaN
3  15.0  16.0  17.0  18.0  19.0 NaN

In [207]:
df1+df2

a     b     c     d   e   p
0   0.0   2.0   5.0   5.0 NaN NaN
1   9.0  11.0  14.0  14.0 NaN NaN
2  18.0  20.0  23.0  23.0 NaN NaN
3   NaN   NaN   NaN   NaN NaN NaN

In [209]:
df1.add(df2,fill_value=0) #df2中不存在时传入0

a     b     c     d     e   p
0   0.0   2.0   5.0   5.0   4.0 NaN
1   9.0  11.0  14.0  14.0   9.0 NaN
2  18.0  20.0  23.0  23.0  14.0 NaN
3  15.0  16.0  17.0  18.0  19.0 NaN

In [210]:
df1

a    b     d     c
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [211]:
1/df1

a         b         d         c
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [212]:
df1.rdiv(1)

a         b         d         c
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [216]:
df1.reindex(columns=df2.columns,fill_value=0) #column为列，索引和列相同，没有的fill_value补充0

a    b     c     d  e  p
0  0.0  1.0   3.0   2.0  0  0
1  4.0  5.0   7.0   6.0  0  0
2  8.0  9.0  11.0  10.0  0  0

In [217]:
arr = np.arange(12).reshape(3,4)

In [218]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [219]:
arr[0]

array([0, 1, 2, 3])

In [220]:
arr - arr[0]

array([[0, 0, 0, 0],
       [4, 4, 4, 4],
       [8, 8, 8, 8]])

In [223]:
frame = pd.DataFrame(np.arange(12).reshape(4,3),columns=list('abe'),index=['Utah','Ohio','Texas','California'])

In [224]:
series = frame.iloc[0]

In [225]:
series

a    0
b    1
e    2
Name: Utah, dtype: int32

In [226]:
frame

a   b   e
Utah        0   1   2
Ohio        3   4   5
Texas       6   7   8
California  9  10  11

In [227]:
frame - series  #会广播

a  b  e
Utah        0  0  0
Ohio        3  3  3
Texas       6  6  6
California  9  9  9

In [228]:
series = pd.Series(range(3),index = ['e','f','g'])

In [229]:
frame2 + series

California  Ohio  Texas   e   f   g
a         NaN   NaN    NaN NaN NaN NaN
b         NaN   NaN    NaN NaN NaN NaN
c         NaN   NaN    NaN NaN NaN NaN
d         NaN   NaN    NaN NaN NaN NaN